### PR TITLE
Combine RS and Indexes to one pool

### LINKED ISSUE #156: Combine Indexes with RS pool
Combine Indexes with RS pool.

### PR DESCRIPTION
**Pull request by KFilipek**
Add new structure Index for record store pool containing all trees for specific RS.
File opening moved from data structures to engine.
Closes #156

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/164)

### CODE REVIEW

**Comment by KFilipek** [comment]
retest this please

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by KFilipek** [comment]
Maybe someone will need it, but for now I decided to clear my PR list.

**Pull request closed without merging**
