### PR TITLE
PMSE unit tests

### PR DESCRIPTION
**Pull request by abonisl**
Signed-off-by: Adrian Bonislawski <adrianx.bonislawski@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/144)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by jschmieg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[SConscript, line 51 at r1](https://reviewable.io:443/reviews/pmem/pmse/144#-KyykXkTSoXihlWzWY5M:-KyykXkU_lZRWDgUEehP:b-vnaxfe) ([raw file](https://github.com/pmem/pmse/blob/d384fd9c10a5d269ed3f125b752d3452e0241b1e/SConscript#L51)):*
> ```Python
>                 ]
>         )
> 		
> ```

Formatting correction: Please remove this empty lines with tabs in it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by KFilipek** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by KFilipek** [comment]
test this please

**Comment by KFilipek** [comment]
ok to test

**Comment by KFilipek** [comment]
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/pmse_standard_record_store_test.cpp, line 70 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wiUQwQuye7I-2VvCk:-L1wiUQwQuye7I-2VvCl:bc0k06j) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_standard_record_store_test.cpp#L70)):*
> ```cpp
> class PmseHarnessHelper final : public RecordStoreHarnessHelper {
>  public:
>   PmseHarnessHelper() : _dbpath("psmem_0"), _engine(_dbpath.path() + "/") {
> ```

delete: + "/"
Look at src/pmse_engine.cpp:56

---

*[src/pmse_standard_record_store_test.cpp, line 80 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wjTMqe1wueNrrMiC4:-L1wjTMrAuIfltN4d_iy:b-usatfr) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_standard_record_store_test.cpp#L80)):*
> ```cpp
>   }
> 
>   virtual std::unique_ptr<RecordStore> newNonCappedRecordStore(
> ```

In some cases we allow to use lines longer than 80 characters (up to 120)
especially for better readability in function arguments and assignments

---

*[src/pmse_standard_record_store_test.cpp, line 94 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wirdmyoY7YqA7JmQH:-L1wirdn-G8ApkxvUht0:b-kwz8ap) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_standard_record_store_test.cpp#L94)):*
> ```cpp
>     std::map<std::string, pool_base> pool_handler;
>     auto ret = stdx::make_unique<PmseRecordStore>(
>         ns, "pool_test", options, _dbpath.path() + "/", &pool_handler);
> ```

the same: src/pmse_engine.cpp:56

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by KFilipek** [comment]
Compiled and looks ok

---

Reviewed 4 of 5 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/pmse_engine_test.cpp, line 54 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wmCW1ExNLiemr-k-H:-L1wmCW1ExNLiemr-k-I:b4bv4qh) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_engine_test.cpp#L54)):*
> ```cpp
>  public:
>   PmseKVHarnessHelper() : _dbpath("psmem_0") {
>     _engine.reset(new PmseEngine(_dbpath.path() + "/"));
> ```

Remove: +"/"

---

*[src/pmse_engine_test.cpp, line 58 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wmW8mZiItlDg_SrKQ:-L1wmW8mZiItlDg_SrKR:bflspkx) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_engine_test.cpp#L58)):*
> ```cpp
> 
>   virtual ~PmseKVHarnessHelper() {
>     _engine.reset(NULL);
> ```

Standard indentation is 4 spaces, public/private/protected stay as is (1 space)

---

*[src/pmse_init_test.cpp, line 2 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wmvkfdmSH8gOr77bi:-L1wmvkfdmSH8gOr77bj:b-ey35o4) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_init_test.cpp#L2)):*
> ```cpp
> /*
>  * Copyright 2014-2017, Intel Corporation
> ```

Year in every file should be changed to 2018

---

*[src/pmse_init_test.cpp, line 34 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wn5VfLg7ZCGTPyOqJ:-L1wn5VfLg7ZCGTPyOqK:bqi29le) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_init_test.cpp#L34)):*
> ```cpp
> 
> #include "mongo/platform/basic.h"
> ```

Every header is from the same group, remove space and sort headers

---

*[src/pmse_init_test.cpp, line 45 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wnKYulu_X_P7kihuw:-L1wnKYulu_X_P7kihux:b-c6p5yz) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_init_test.cpp#L45)):*
In some files are these lines: 
> namespace mongo {
> namespace {

---

*[src/pmse_init_test.cpp, line 88 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wnc3IBumQnb-GGlas:-L1wnc3IBumQnb-GGlat:b9f4i33) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_init_test.cpp#L88)):*
> ```cpp
>   StorageGlobalParams storageOptions;
>   storageOptions.directoryperdb = directoryPerDB;
>   // wiredTigerGlobalOptions.directoryForIndexes = directoryForIndexes;
> ```

Should be still commented? If not please remove it

---

*[src/pmse_record_store_test.cpp, line 176 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wqIhlIrS22Z9L0Zwm:-L1wqIhlIrS22Z9L0Zwn:b-1m9nql) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_record_store_test.cpp#L176)):*
> ```cpp
>   unique_ptr<RecordStoreHarnessHelper> harnessHelper(
>       newRecordStoreHarnessHelper());
>   unique_ptr<RecordStore> rs(
> ```

One line

---

*[src/pmse_standard_record_store_test.cpp, line 37 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wnvxMhPM-_Ix3nCcv:-L1wnvxMhPM-_Ix3nCcw:b-64v784) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_standard_record_store_test.cpp#L37)):*
> #include <libpmemobj++/p.hpp>
> #include <libpmemobj++/persistent_ptr.hpp>
> #include <libpmemobj++/pool.hpp>

Divide headers into groups, look at mongodb files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144#-:-L1wqNXlPTUh_Jqzbt2U:bycil7)*

**Comment by KFilipek** [comment]
PR #154 should be merged earlier, without it some unittests will fail.

**Comment by abonisl** [comment]
Review status: 5 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/pmse_standard_record_store_test.cpp, line 70 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wiUQwQuye7I-2VvCk:-L24o2g52_TTPJJfZ1lU:bvsjrdq) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_standard_record_store_test.cpp#L70)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

delete: + "/"
Look at src/pmse_engine.cpp:56
</blockquote></details>

Are you sure? I think we need to have "/". The dbpath is a generated temp path for each test, for example: "/tmp/psmem_0-f2dfjw" and WITHOUT extra "/" pmse_engine.cpp at line 54: std::string path = _dbPath+_kIdentFilename.toString(); will create 'path' variable (for example) "/tmp/psmem_0-f2dfjwpool_test" which is not a new file in generated directory but a new file "psmem_0-f2dfjwpool_test" in "/tmp/" directory and it will not be deleted at the end of the test execution. Only generated "/tmp/psmem_0-f2dfjw" will be deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by KFilipek** [comment]
Review status: 5 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/pmse_standard_record_store_test.cpp, line 94 at r3](https://reviewable.io:443/reviews/pmem/pmse/144#-L1wirdmyoY7YqA7JmQH:-L2P-cz0syMT2v7wKQXL:bhpfrc3) ([raw file](https://github.com/pmem/pmse/blob/fc6f093e80874f47443c771f6723ba247c62c957/src/pmse_standard_record_store_test.cpp#L94)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

the same: src/pmse_engine.cpp:56
</blockquote></details>

Nevermind, this one is ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by KFilipek** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/pmse_engine_test.cpp, line 62 at r4](https://reviewable.io:443/reviews/pmem/pmse/144#-L3hCmWrh-M4vkFmSc91:-L3hCmWseeUfbXV8PSxa:b-1e51m6) ([raw file](https://github.com/pmem/pmse/blob/bbbbf69269ca9669968f9b9c8fc7edb43da94f78/src/pmse_engine_test.cpp#L62)):*
> ```cpp
> 
>     virtual KVEngine* restartEngine() {
>         _engine.reset(NULL);
> ```

unique_ptr call deleter on non-empty pointer, so there is no reason to do reset(NULL);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/144)*

**Comment by KFilipek** [comment]
When you will push new commit please do rebase, there are some changes that may fix some tests (e.g. RestartForPrefixes from pmse_engine_test)

**Pull request merged**
