### PR TITLE
Fix capped restore for tailable cursors

### PR DESCRIPTION
**Pull request by KFilipek**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/151)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/151)*

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by kasiawasiuta** [comment]
retest this please

**Comment by abonisl** [comment]
This patch will fix CappedPositionLost issue but also will fail gre/core/remove5.js test (probably not only this   one).

**Comment by KFilipek** [comment]
Maybe someone will need it, but for now I decided to clear my PR list.

**Pull request closed without merging**
