### PR TITLE
Now all tests from given suite are run

### PR DESCRIPTION
**Pull request by kasiawasiuta**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/147)

### CODE REVIEW

**Comment by llugin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[run-jstests.py, line 43 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-EMfqNNXMD6svHTZk:-Kz-EMfqNNXMD6svHTZl:bfd9yxi) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L43)):*
> ```Python
> 
> 
> def getTestsForSuite(suite, mongo_root):
> ```

pls use snake_case

---

*[run-jstests.py, line 44 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-Ep6kxI0iuHSG-IEj:-Kz-Ep6kxI0iuHSG-IEk:b-4fhzt4) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L44)):*
> ```Python
> 
> def getTestsForSuite(suite, mongo_root):
>     cmd = test_binary[:]
> ```

Pls don't refer to non-local variables (test_binary) inside functions, it's not a good practice.

---

*[run-jstests.py, line 46 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-FLT7dwOd39mZQMpy:-Kz-FLT7dwOd39mZQMpz:b7lu9os) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L46)):*
>    cmd.append('--suites={}'.format(suite))
>    cmd.append('-n')

use extend() to append list to list

---

*[run-jstests.py, line 50 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-J5R2gEAlKozcstrM:-Kz-J5R2gEAlKozcstrN:bqj42k0) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L50)):*
> ```Python
>     out = proc.stdout.decode('utf-8').splitlines()
> 
>     regex = re.compile(r"^jstests[\w/_]+.*js")
> ```

maybe if startswith('jstests') and endswith('.js') ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147)*

**Comment by kasiawasiuta** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[run-jstests.py, line 43 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-EMfqNNXMD6svHTZk:-Kz30-DJZxUr0o3rs0ID:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L43)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

pls use snake_case
</blockquote></details>

Done.

---

*[run-jstests.py, line 44 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-Ep6kxI0iuHSG-IEj:-Kz3AnzS7PNFNEKr9FvC:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L44)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

Pls don't refer to non-local variables (test_binary) inside functions, it's not a good practice.
</blockquote></details>

Done.

---

*[run-jstests.py, line 50 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-J5R2gEAlKozcstrM:-Kz30eNaRtBmxf_5bL4U:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L50)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

maybe if startswith('jstests') and endswith('.js') ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147)*

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147)*

**Comment by llugin** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147#-:-Kz41c0cFdPIxL2o_WBf:bnfp4nl)*

**Comment by llugin** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147)*

**Comment by kasiawasiuta** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[run-jstests.py, line 46 at r1](https://reviewable.io:443/reviews/pmem/pmse/147#-Kz-FLT7dwOd39mZQMpy:-Kz3vPzKqXbzkRtWuGpn:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/40e69b0a6a89bdb088a871d9aaeaca098a09672c/run-jstests.py#L46)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

>    cmd.append('--suites={}'.format(suite))
>    cmd.append('-n')

use extend() to append list to list

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/147)*

**Pull request merged**
