### PR TITLE
Add checks to prevent segmentation fault at inserts

### PR DESCRIPTION
**Pull request by KFilipek**
Prevent segmentation fault at inserts when there is no space left on device.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/103)

### CODE REVIEW

**Comment by jschmieg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/103)*

**Comment by KFilipek** [comment]
Conflicts are solved, but change need to be compiled/tested separetely.

**Comment by krzycz** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pmse_record_store.cpp, line 133 at r2](https://reviewable.io:443/reviews/pmem/pmse/103#-KtVL68VSMIz0I-0Px2z:-KtVL68VSMIz0I-0Px3-:b-cixrpc) ([raw file](https://github.com/pmem/pmse/blob/40e9c6049a473b910cc9678c5e795a85b2264fe0/src/pmse_record_store.cpp#L133)):*
> ```cpp
>         transaction::exec_tx(_mapPool, [this, &obj, len, data, &id] {
>             obj = pmemobj_tx_alloc(sizeof(InitData::size) + len, 1);
>         });
> ```

For me, it looks like replacing a fuse with a nail...
Am I missing something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/103)*

**Comment by krzycz** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/103)*

**Comment by jschmieg** [comment]
Should be corrected together with #111

**Pull request closed without merging**
