### PR TITLE
Initialization flag for Mapper

### LINKED ISSUE #127: Fault-tolerant initialization in Mapper
There is need to implement safe initization for mapper in case of crash during initialize().

### PR DESCRIPTION
**Pull request by KFilipek**
Closes #127

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/134)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/134)*

**Comment by jschmieg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/pmse_record_store.cpp, line 115 at r1](https://reviewable.io:443/reviews/pmem/pmse/134#-KwdC85cwUx1VfOSksd-:-KwdC85cwUx1VfOSksd0:b-n30tye) ([raw file](https://github.com/pmem/pmse/blob/20282f9a32adf0d74ef724c57fb6820ff15593c5/src/pmse_record_store.cpp#L115)):*
> ```cpp
>         _mapper = mapper_root->kvmap_root_ptr;
>         if (_mapper->isInitialized()) {
>             _mapper->initialize(false);
> ```

In case of crash during initialization there is persistent memory leak on already allocated objects. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/134)*

**Comment by KFilipek** [comment]
I pushed forced update to my changes.

**Comment by KFilipek** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pmse_record_store.cpp, line 115 at r1](https://reviewable.io:443/reviews/pmem/pmse/134#-KwdC85cwUx1VfOSksd-:-KwduRmb1Kfq8UhKl-Lc:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/20282f9a32adf0d74ef724c57fb6820ff15593c5/src/pmse_record_store.cpp#L115)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

In case of crash during initialization there is persistent memory leak on already allocated objects. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/134)*

**Comment by jschmieg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/pmse_map.h, line 174 at r2](https://reviewable.io:443/reviews/pmem/pmse/134#-KwiKGt1vytYkw0sxLK8:-KwiKGt2L2o9Dyam_dPA:beolikv) ([raw file](https://github.com/pmem/pmse/blob/997f7ed8d93962351e13f05851ed4cf8d0ccb0df/src/pmse_map.h#L174)):*
> ```objc
>                     transaction::exec_tx(pop, [this, i] {
>                         _list[i] = make_persistent<PmseListIntPtr>();
>                         _toInitialize = i;
> ```

What about making one big transaction to initialize mapper instead of many small transaction? It will simplify restore after crash during initialization and slightly decrease creating new collection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/134)*

**Comment by KFilipek** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/pmse_map.h, line 174 at r2](https://reviewable.io:443/reviews/pmem/pmse/134#-KwiKGt1vytYkw0sxLK8:-KwiURT0IoJEeWVMI9Mr:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/997f7ed8d93962351e13f05851ed4cf8d0ccb0df/src/pmse_map.h#L174)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

What about making one big transaction to initialize mapper instead of many small transaction? It will simplify restore after crash during initialization and slightly decrease creating new collection.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/134)*

**Pull request merged**
