### PR TITLE
Removal from index tree and tree balancing

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/8)

### CODE REVIEW

**Comment by Maciuch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/pmse_sorted_data_interface.cpp, line 53 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ZFkxiU7d_NHJs63pl:-K_ZFkxiU7d_NHJs63pm:b-u9p8mw) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L53)):*
> ```cpp
>                const bool unique) :
>                     _forward(isForward), _ordering(ordering),
>                     //_root(tree->root),
> ```

remove comment

---

*[src/pmse_sorted_data_interface.cpp, line 460 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ZGKQ4o17_x1zajaTX:-K_ZGKQ4o17_x1zajaTY:b-brcy1y) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L460)):*
> ```cpp
>                     _tree->_cursor.node = nullptr;
>                 }
> ```

excess line

---

*[src/pmse_tree.cpp, line 62 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ij7-TZLLJteRaGvn1:-K_ij7-TZLLJteRaGvn2:b7qyt21) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_tree.cpp#L62)):*
> ```cpp
>     node = locateLeafWithKey(root, key, _ordering);
>     //find place in node
>     for (i = 0; i < node->num_keys; i++) {
> ```

if the node is not found two lines up, this will dereference a null pointer

---

*[src/pmse_tree.cpp, line 65 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ihxkvFyIuKry_fC31:-K_ihxkvFyIuKry_fC32:b-vqeu4w) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_tree.cpp#L65)):*
> ```cpp
>         key_record = node->values_array[i];
>         cmp = key.woCompare(node->keys[i].getBSON(), _ordering, false);
>         if (cmp == 0) {
> ```

hypothetically, if compare for entire loop will not find a key, deleteEntry() will be called with the last key from the loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/8)*

**Comment by KFilipek** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/pmse_sorted_data_interface.cpp, line 49 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7FQz9ZypGTzcBf6TJ:-Ka7FQzAwhtwcZ7AcFGN:b-7cyqw3) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L49)):*
> ```cpp
> class PmseCursor final : public SortedDataInterface::Cursor {
> public:
>     PmseCursor(OperationContext* txn, bool isForward,
> ```

Extract PmseCursor to other file .h/.cpp.
Or put declaration to .h file. Cursor implementation takes 700 lines of code.

---

*[src/pmse_sorted_data_interface.cpp, line 71 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7Ga9VMnyUKp-6MFad:-Ka7Ga9VMnyUKp-6MFae:b-f8msz1) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L71)):*
> ```cpp
>         max = maxBob.obj();
>     }
>     ;
> ```

After each foo() {} semicolon is not needed anymore.

---

*[src/pmse_sorted_data_interface.cpp, line 323 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka2lt1GnANm-IMyfKAR:-Ka2lt1GnANm-IMyfKAS:b-p1hsy5) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L323)):*
> ```cpp
>         }
>         if (_tree->_cursor.node == nullptr)
>             return {};
> ```

Change every return {}; to return boost::none;
MongoDB mostly use this as return type.

---

*[src/pmse_sorted_data_interface.cpp, line 333 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka3CmFgeKIVwmUKEaQQ:-Ka3CmFgeKIVwmUKEaQR:b-v6ss36) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L333)):*
> if (_endPosition
> && (SimpleBSONObjComparator::kInstance.evaluate(
To one line. I prepare new rules to code formatting.

---

*[src/pmse_sorted_data_interface.cpp, line 335 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka2n9GkQX5AGFTHbPvH:-Ka2n9GkQX5AGFTHbPvI:b-6rkri4) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L335)):*
> (*_endPosition).getBSON())
Change to all above to: _endPosition->getBSON()

---

*[src/pmse_sorted_data_interface.cpp, line 339 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka2nJFBLd3zfvG1LHjr:-Ka2nJFBLd3zfvG1LHjs:b-lwqo1u) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L339)):*
> if (correctType(
> _tree->_cursor.node->keys[_tree->_cursor.index].getBSON())) {
should be in one line

---

*[src/pmse_sorted_data_interface.cpp, line 721 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7GwEtlO_E690oBhSM:-Ka7GwEtlO_E690oBhSN:bjhwdpm) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L721)):*
> boost::optional<IndexKeyEntry> seekExact(const BSONObj& key,
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>                                              RequestedInfo parts = kKeyAndLoc) {
>         auto kv = seek(key, true, kKeyAndLoc);
>         if (kv && kv->key.woCompare(key, BSONObj(), /*considerFieldNames*/
>         false) == 0)
>             return kv;
>         return {};
</details>
Code duplication from interface.

---

*[src/pmse_sorted_data_interface.cpp, line 786 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7Hfw7ijHuMc2mhZi5:-Ka7Hfw7ijHuMc2mhZi6:b-jr3l64) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L786)):*
> ```cpp
> 
>     if (access(filename.c_str(), F_OK) != 0) {
>         pm_pool = pool<PmseTree>::create(filename.c_str(), "pmStore",
> ```

"pmStore" is not used anymore. Use "pmse" instead.

---

*[src/pmse_sorted_data_interface.cpp, line 810 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7eQk48Kc82ZqHdFYK:-Ka7eQk48Kc82ZqHdFYL:bfacuuh) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L810)):*
> auto pop = pool_base(pm_pool);
>     try {
>         transaction::exec_tx(pop,
Use pm_pool for transactions, don't create new objects. tree->insert(pop,[...]) and tree->remove(pm_pool,[...])

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/8)*

**Comment by KFilipek** [comment]
Review status: 0 of 4 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/pmse_sorted_data_interface.cpp, line 35 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7wm9eoaBb_AUJdTNt:-Ka7wm9fq79rdRTZkGBH:bczoeih) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L35)):*
>  
> #include "mongo/platform/basic.h"
> #include "mongo/db/storage/sorted_data_interface.h"
> #include "mongo/bson/simple_bsonobj_comparator.h"
> #include "mongo/util/log.h"
> #include "mongo/stdx/memory.h"
This includes are not necessary

---

*[src/pmse_sorted_data_interface.cpp, line 41 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7x1r6OiXKzAWCl3yl:-Ka7x1r6OiXKzAWCl3ym:bw291nm) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L41)):*

> #include "errno.h"
> #include "libpmemobj++/transaction.hpp"
This includes are not necessary

---

*[src/pmse_tree.cpp, line 527 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka81cWoEpZRLzS5_xE4:-Ka81cWpHTunHhyCtXeR:bk3ghvv) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_tree.cpp#L527)):*
> persistent_ptr<PmseTreeNode> current = node;
Second copy of the same object - first is done when you pass arguments. Prefer auto instead of full declaration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/8)*

**Comment by jschmieg** [comment]
Review status: 0 of 6 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/pmse_sorted_data_interface.cpp, line 333 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka3CmFgeKIVwmUKEaQQ:-KaHSlHb5jdvDp3tM_f5:b43ow6q) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L333)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> if (_endPosition
> && (SimpleBSONObjComparator::kInstance.evaluate(
To one line. I prepare new rules to code formatting.
</blockquote></details>

No sense to correct it now. Every "Source-> format" is modifying it back.

---

*[src/pmse_sorted_data_interface.cpp, line 339 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka2nJFBLd3zfvG1LHjr:-KaHSzM_2eH4DPJL7A4x:b43ow6q) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L339)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> if (correctType(
> _tree->_cursor.node->keys[_tree->_cursor.index].getBSON())) {
should be in one line

</blockquote></details>

No sense to correct it now. Every "Source-> format" is modifying it back.

---

*[src/pmse_tree.cpp, line 62 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ij7-TZLLJteRaGvn1:-KaHa3lijdKE6GwZLn1l:b-ml40cq) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_tree.cpp#L62)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

if the node is not found two lines up, this will dereference a null pointer
</blockquote></details>

Such situation shouldn't occur. If tree is empty, seek() will return null and Mongo will not call remove(). But I added additional check on empty root.

---

*[src/pmse_tree.cpp, line 65 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ihxkvFyIuKry_fC31:-KaHaYQ7PTheqVln7qX0:b3plzzy) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_tree.cpp#L65)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

hypothetically, if compare for entire loop will not find a key, deleteEntry() will be called with the last key from the loop?
</blockquote></details>

Before Mongo calls "unindex" it calls "seek" from SortedDataInterface. Only if record is found it will call "unindex" on it.

---

*[src/pmse_tree.cpp, line 527 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka81cWoEpZRLzS5_xE4:-KaHcQIpF9kQuOAQaOeU:b-ml7hpn) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_tree.cpp#L527)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> persistent_ptr<PmseTreeNode> current = node;
Second copy of the same object - first is done when you pass arguments. Prefer auto instead of full declaration.
</blockquote></details>

 I modified method to not pass node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/8)*

**Comment by jschmieg** [comment]
Review status: 0 of 12 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/pmse_sorted_data_interface.cpp, line 35 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7wm9eoaBb_AUJdTNt:-KaN-q57Zjty6GY6BL4y:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

>  
> #include "mongo/platform/basic.h"
> #include "mongo/db/storage/sorted_data_interface.h"
> #include "mongo/bson/simple_bsonobj_comparator.h"
> #include "mongo/util/log.h"
> #include "mongo/stdx/memory.h"
This includes are not necessary
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 41 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7x1r6OiXKzAWCl3yl:-KaN-rVgXFSjl3jYbhLO:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L41)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>


> #include "errno.h"
> #include "libpmemobj++/transaction.hpp"
This includes are not necessary
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 49 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7FQz9ZypGTzcBf6TJ:-KaN-wu9Cyu2dbvMVJaX:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L49)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Extract PmseCursor to other file .h/.cpp.
Or put declaration to .h file. Cursor implementation takes 700 lines of code.
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 53 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ZFkxiU7d_NHJs63pl:-KaN-xi-GtPSCwZ3eDjF:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L53)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 71 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7Ga9VMnyUKp-6MFad:-KaN-yiRadJePfK2qMld:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L71)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

After each foo() {} semicolon is not needed anymore.
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 323 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka2lt1GnANm-IMyfKAR:-KaN-zYAtr3KhymiAa15:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L323)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Change every return {}; to return boost::none;
MongoDB mostly use this as return type.
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 335 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka2n9GkQX5AGFTHbPvH:-KaN03GUpks3S2oJFpHk:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L335)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> (*_endPosition).getBSON())
Change to all above to: _endPosition->getBSON()
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 460 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-K_ZGKQ4o17_x1zajaTX:-KaN0BCTQ27NZn3-uPoC:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L460)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

excess line
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 721 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7GwEtlO_E690oBhSM:-KaN07QoVZxDgeggiRIG:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L721)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> boost::optional<IndexKeyEntry> seekExact(const BSONObj& key,
>                                              RequestedInfo parts = kKeyAndLoc) {
>         auto kv = seek(key, true, kKeyAndLoc);
>         if (kv && kv->key.woCompare(key, BSONObj(), /*considerFieldNames*/
>         false) == 0)
>             return kv;
>         return {};
Code duplication from interface.
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 786 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7Hfw7ijHuMc2mhZi5:-KaN08lo0v7W8RSu4HyP:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L786)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

"pmStore" is not used anymore. Use "pmse" instead.
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 810 at r1](https://reviewable.io:443/reviews/pmem/pmse/8#-Ka7eQk48Kc82ZqHdFYK:-KaN0ANw3fQOx89lZlFz:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/5df591bec3a9d9f07177a1517357d0f52b80bccc/src/pmse_sorted_data_interface.cpp#L810)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> auto pop = pool_base(pm_pool);
>     try {
>         transaction::exec_tx(pop,
Use pm_pool for transactions, don't create new objects. tree->insert(pop,[...]) and tree->remove(pm_pool,[...])
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/8)*

**Pull request merged**
