### PR TITLE
Record Cursor: Reverse cursor

### PR DESCRIPTION
**Pull request by KFilipek**
Fixed most tests in issue: #25.

Still not passing, but it's not related to this commit:
```
fts_mix.js
fts_querylong.js
geo1.js
index13.js
sortc.js
sortg.js

```
Fixes: #25

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/29)

### CODE REVIEW

**Comment by jschmieg** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pmse_record_store.cpp, line 350 at r1](https://reviewable.io:443/reviews/pmem/pmse/29#-Kc3OJNmJxwp5Qgsk52Q:-Kc3OJNnRUSsj_jyafeZ:bvcqqev) ([raw file](https://github.com/pmem/pmse/blob/dfe5e17f2eb45012983501ee8305a2f5f755502b/src/pmse_record_store.cpp#L350)):*
> ```cpp
>         int lastNonEmpty = -1;
>         int scope = (actual < 0 ? _mapper->_size : static_cast<int>(actual));
>         for (int i = 0; i < scope; ++i) {
> ```

Maybe use some fixed width int: int64_t, uint64_t http://en.cppreference.com/w/cpp/types/integer
as in the rest of code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/29)*

**Comment by KFilipek** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pmse_record_store.cpp, line 350 at r1](https://reviewable.io:443/reviews/pmem/pmse/29#-Kc3OJNmJxwp5Qgsk52Q:-Kc3Tzv8tTN0G1VzyZrX:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/dfe5e17f2eb45012983501ee8305a2f5f755502b/src/pmse_record_store.cpp#L350)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

Maybe use some fixed width int: int64_t, uint64_t http://en.cppreference.com/w/cpp/types/integer
as in the rest of code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/29)*

**Comment by jschmieg** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/29#-:-KcHyd-cxWWPD6-jvDsI:bnfp4nl)*

**Comment by Maciuch** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/29)*

**Pull request merged**
