### PR TITLE
Correction in next: check type of next object

### PR DESCRIPTION
**Pull request by jschmieg**
Corrects:
all.js
and.js
arrayfind8.js
countc.js
idhack.js
in3.js
index13.js
mod1.js
or1.js
or6.js

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/51)

### CODE REVIEW

**Comment by Maciuch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pmse_index_cursor.cpp, line 316 at r1](https://reviewable.io:443/reviews/pmem/pmse/51#-KdeFNK9AO3RHxbpS2Og:-KdeFNK9AO3RHxbpS2Oh:b37z23h) ([raw file](https://github.com/pmem/pmse/blob/e568cb17bd0988cac606e6afacf6d18f65581125/src/pmse_index_cursor.cpp#L316)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     if (!_tree->root) {
>         return boost::none;
>     }
>     if (_cursor.node == nullptr)
>         return boost::none;
</details>
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     if (_eofRestore)
>     {
>         _eofRestore= false;
>         return boost::none;
>     }
</details>

As this method is being touched, it would be nice to align coding styles for those 3 if-s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/51)*

**Comment by jschmieg** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/pmse_index_cursor.cpp, line 316 at r1](https://reviewable.io:443/reviews/pmem/pmse/51#-KdeFNK9AO3RHxbpS2Og:-KdeRUknCkANgmvpFeV7:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/e568cb17bd0988cac606e6afacf6d18f65581125/src/pmse_index_cursor.cpp#L316)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

>     if (!_tree->root) {
>         return boost::none;
>     }
>     if (_cursor.node == nullptr)
>         return boost::none;
>  
>     if (_eofRestore)
>     {
>         _eofRestore= false;
>         return boost::none;
>     }

As this method is being touched, it would be nice to align coding styles for those 3 if-s
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/51)*

**Comment by KFilipek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/51#-:-KdetGS3IanuhldoJ2vC:bnfp4nl)*

**Comment by jschmieg** [comment]
Fixes #41

**Pull request merged**
