### PR TITLE
Set of scripts to benchmarking automatization

### PR DESCRIPTION
**Pull request by KFilipek**
This PR provide set of script to automatize benchmarking.
User can write complete benchmarking scenario using some predefined keywords.
All tests parameters are enclosed in a single suite, e.g.
```
SUITE test_load_workload
THREADS 4
LOAD
JOURNALING disabled
RECORDS 10000
OPERATIONS 5000
READ_PROPORTION 1.0
UPDATE_PROPORTION 0.0
INSERT_PROPORTION 0.0
YCSB_NUMA -1
CREATE_AFTER_DROP
ENDSUITE
```
One configuration file can provide multiple suites running one by one.
Explanation of keywords, rules etc will be provided in README.md file later in this pull request.
File explanation:
**path_configuration.txt** - file contains full paths for YCSB and MongoDB
**run_suite.py** will generate bash file with commands to run YCSB in various configurations.
**run_workload.sh** - bash file which is called from _testplan.sh_ generated by _run_suite.py_
**test_suite.txt** - set of user-defined suites, file is created by user.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/149)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/149)*

**Comment by llugin** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[utils/run_suite.py, line 202 at r1](https://reviewable.io:443/reviews/pmem/pmse/149#-KzhiEMtfrJtiau-jstx:-KzhiEMtfrJtiau-jsty:b-bfpx3d) ([raw file](https://github.com/pmem/pmse/blob/c5616c533e20d78e98481416d93105929b934ade/utils/run_suite.py#L202)):*
>    if test.ycsb_numa == -1:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         print 'NUMA node is not set for test: ' + test.testName + '.'
>         command_suffix += test.ycsb_numa
>     else:
>         command_suffix += test.ycsb_numa
</details>

how about: 
if test.ycsb_numa == -1:
         print 'NUMA node is not set for test: ' + test.testName + '.'
command_suffix += test.ycsb_numa

---

*[utils/run_suite.py, line 217 at r1](https://reviewable.io:443/reviews/pmem/pmse/149#-KzhhSsZV45NdGlBGmAH:-KzhhSsZV45NdGlBGmAI:b5x2r3r) ([raw file](https://github.com/pmem/pmse/blob/c5616c533e20d78e98481416d93105929b934ade/utils/run_suite.py#L217)):*
> testplan = open('testplan.sh','w')
> testplan.write('#!/bin/bash\n')
> for x in generated_commands:
>     testplan.write(x + '\n')
> testplan.close()

consider using with open(..) context manager (in other places as well) https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/149)*

**Comment by KFilipek** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[utils/run_suite.py, line 202 at r1](https://reviewable.io:443/reviews/pmem/pmse/149#-KzhiEMtfrJtiau-jstx:-KzhkDVEOvg0K3MfQ095:bblblcy) ([raw file](https://github.com/pmem/pmse/blob/c5616c533e20d78e98481416d93105929b934ade/utils/run_suite.py#L202)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

>    if test.ycsb_numa == -1:
>         print 'NUMA node is not set for test: ' + test.testName + '.'
>         command_suffix += test.ycsb_numa
>     else:
>         command_suffix += test.ycsb_numa

how about: 
if test.ycsb_numa == -1:
         print 'NUMA node is not set for test: ' + test.testName + '.'
command_suffix += test.ycsb_numa

</blockquote></details>

Right, I will fix it

---

*[utils/run_suite.py, line 217 at r1](https://reviewable.io:443/reviews/pmem/pmse/149#-KzhhSsZV45NdGlBGmAH:-Kzhkf3GtwjnSrZOtnCk:b-on8pef) ([raw file](https://github.com/pmem/pmse/blob/c5616c533e20d78e98481416d93105929b934ade/utils/run_suite.py#L217)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

> testplan = open('testplan.sh','w')
> testplan.write('#!/bin/bash\n')
> for x in generated_commands:
>     testplan.write(x + '\n')
> testplan.close()

consider using with open(..) context manager (in other places as well) https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects
</blockquote></details>

That's good idea, I will apply it on new version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/149)*

**Comment by kasiawasiuta** [comment]
retest this please

**Pull request merged**
