### PR TITLE
Index with save and restore. Corrections in Tree balancing.

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/22)

### CODE REVIEW

**Comment by KFilipek** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/pmse_index_cursor.cpp, line 142 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPqC5Z0sCx2tJl7LZJ:-KbPqC5Z0sCx2tJl7LZK:b-cuhoeu) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L142)):*
> ```cpp
>      */
>     persistent_ptr<PmseTreeNode> node = find_leaf(_tree->root, key, _ordering);
> ```

remove additional empty lines

---

*[src/pmse_index_cursor.cpp, line 315 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPl6zn9thLwd6ES0fd:-KbPl6zn9thLwd6ES0fe:bmsxku8) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L315)):*
> ```cpp
>         return boost::none;
> 
>     if(_eofRestore)
> ```

'if' above have space before bracket and '{' in the same line. The same case in another if's.

---

*[src/pmse_index_cursor.cpp, line 330 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPljvBO4CRpgoRgUUU:-KbPljvBO4CRpgoRgUUV:b-onv83g) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L330)):*
>    if (_endPosition
>                                   && (SimpleBSONObjComparator::kInstance.evaluate( 
to one line, this layout don't improve anything

---

*[src/pmse_index_cursor.cpp, line 336 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPnqOxqE6gQIxRq9lT:-KbPnqOxqE6gQIxRq9lU:bh7oxmz) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L336)):*
> return IndexKeyEntry(_cursor.node->keys[_cursor.index].getBSON(),
This form don't extend 80's characters in line. Please apply in similar.

---

*[src/pmse_index_cursor.cpp, line 642 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPpwidJiQmKOecmYVA:-KbPpwidJiQmKOecmYVB:b7r5xui) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L642)):*
> ```cpp
> 
>         }
>     }                //if(_forward){
> ```

Comment

---

*[src/pmse_index_cursor.h, line 97 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPpa72QlN-TlufzEo2:-KbPpa73OFPwG0V4QEK6:b-4stfp8) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.h#L97)):*
> ```objc
>     RecordId _cursorId;
> 
>     bool wasMoved;
> ```

_wasMoved

---

*[src/pmse_tree.cpp, line 219 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbQ9kc0W71eg2jEdXpK:-KbQ9kc0W71eg2jEdXpL:bmv59tw) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L219)):*
> ```cpp
>             if (bsonPM.data.raw().off != 0)
>             {
>                 pmemobj_tx_free(bsonPM.data.raw());
> ```

According to documentation: "this function must be called during TX_STAGE_WORK".
Put it in transaction.

---

*[src/pmse_tree.cpp, line 222 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbQAs_WtBmaSnacXPC_:-KbQAs_XUCQ39UjzAFAB:bmy5lu6) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L222)):*
> ```cpp
>             }
> 
>             bsonPM.data = obj;
> ```

What will happen when allocation above fails?

---

*[src/pmse_tree.cpp, line 241 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbQFX8M4tcO0wZjIH3M:-KbQFX8NyClSFWkax9Fv:b-lnhaxd) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L241)):*
> ```cpp
>             BSONObj_PM bsonPM;
>             persistent_ptr<char> obj;
>             transaction::exec_tx(pop,
> ```

Delete unnecessary transactions

---

*[src/pmse_tree.cpp, line 292 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPu6fsLXJ2Emf4t090:-KbPu6ftkMA2xuhhtuYI:bdstvgz) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L292)):*
> /*if (_cursor.node == neighbor) {
>         _cursor.node = n;
>         _cursor.index = 0;
>     }*/
Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/22)*

**Comment by jschmieg** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/pmse_index_cursor.cpp, line 330 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPljvBO4CRpgoRgUUU:-KbjlJ1qZjqKrbFPN7hK:bc6bjtl) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L330)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

>    if (_endPosition
>                                   && (SimpleBSONObjComparator::kInstance.evaluate( 
to one line, this layout don't improve anything
</blockquote></details>

It is automatic eclipse formatting

---

*[src/pmse_index_cursor.cpp, line 642 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPpwidJiQmKOecmYVA:-KbjldFbsKGKdCPF6ZI6:b-x6ddft) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L642)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

It is for visibility purpose. It shows which "if" is closed by this bracket.

---

*[src/pmse_tree.cpp, line 219 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbQ9kc0W71eg2jEdXpK:-KbjmDSv5TntwdO_bgk_:b-ypkzio) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L219)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

According to documentation: "this function must be called during TX_STAGE_WORK".
Put it in transaction.
</blockquote></details>

This is inside transaction started in caller function.

---

*[src/pmse_tree.cpp, line 222 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbQAs_WtBmaSnacXPC_:-Kbjn9oeBVS_8-4mHNrM:bwaclag) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L222)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

What will happen when allocation above fails?
</blockquote></details>

Issue #23 

---

*[src/pmse_tree.cpp, line 241 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbQFX8M4tcO0wZjIH3M:-KbjmxhQKmf6y16Vwnt1:b-rzoyif) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L241)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Delete unnecessary transactions
</blockquote></details>

I added Issue #23 to correct it everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/22)*

**Comment by jschmieg** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/pmse_index_cursor.cpp, line 142 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPqC5Z0sCx2tJl7LZJ:-KbnmzGr-2Pj_-p_en1q:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L142)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove additional empty lines
</blockquote></details>

Done.

---

*[src/pmse_index_cursor.cpp, line 315 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPl6zn9thLwd6ES0fd:-Kbnn5h1NCD0nMfnYSxT:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L315)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

'if' above have space before bracket and '{' in the same line. The same case in another if's.
</blockquote></details>

Done.

---

*[src/pmse_index_cursor.cpp, line 336 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPnqOxqE6gQIxRq9lT:-KbnnMux6yszOGqoNRtE:b-u91yox) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.cpp#L336)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> return IndexKeyEntry(_cursor.node->keys[_cursor.index].getBSON(),
This form don't extend 80's characters in line. Please apply in similar.
</blockquote></details>

Automatic formatting

---

*[src/pmse_index_cursor.h, line 97 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPpa72QlN-TlufzEo2:-KbnnAynNACJDA0815By:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_index_cursor.h#L97)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

_wasMoved
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/22)*

**Comment by jschmieg** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/pmse_tree.cpp, line 292 at r1](https://reviewable.io:443/reviews/pmem/pmse/22#-KbPu6fsLXJ2Emf4t090:-Kbno2smwrazdJtDd_Xe:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/34e8edcd92d777ebd3ee647e245471b6649cf65f/src/pmse_tree.cpp#L292)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> /*if (_cursor.node == neighbor) {
>         _cursor.node = n;
>         _cursor.index = 0;
>     }*/
Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/22)*

**Comment by jschmieg** [comment]
Reviewed 1 of 5 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/22)*

**Comment by KFilipek** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/22#-:-KbnofDwe7pjgmXuHLC-:bnfp4nl)*

**Pull request merged**
