### PR TITLE
Index rollback

### PR DESCRIPTION
**Pull request by jschmieg**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/38)

### CODE REVIEW

**Comment by KFilipek** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/pmse_change.cpp, line 101 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQLBLTK2TRo-hAY9W5:-KdQLBLTK2TRo-hAY9W6:b-ygtgux) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_change.cpp#L101)):*
> ```cpp
>             log() << e.what();
>         }
>         id = _mapper->updateKV(_key, obj);
> ```

If try or transaction fails what if?
_mapper->updateKV will add empty object.

---

*[src/pmse_change.cpp, line 123 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQKOMpCDCfZWhgn-IY:-KdQKOMpCDCfZWhgn-IZ:b-6ltbxc) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_change.cpp#L123)):*
>                             [&] {
>                                 _tree->remove(_pop, _key, _loc, _dupsAllowed, _desc->keyPattern(), nullptr);
>                                 --(_tree->_records);
Strange formatting. 
Lambda function is still parameter, look above

---

*[src/pmse_change.cpp, line 152 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQNoLHpRdtLY3HEdp7:-KdQNoLIfOv6q4vNlkg9:b-bhrsik) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_change.cpp#L152)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>
>        [&] {
>                                 obj = pmemobj_tx_alloc(_key.objsize(), 1);
>                                 memcpy( (void*)obj.get(), _key.objdata(), _key.objsize());
>                                 bsonPM.data = obj;
>                                 status = _tree->insert(_pop, bsonPM, _loc, _ordering, _dupsAllowed);
>                                 if(status == Status::OK())
>                                 {
>                                     ++_tree->_records;
>                                 }
</details>
Indentation

---

*[src/pmse_tree.h, line 123 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQOkFu4BLuOLpiuh6l:-KdQOkFvbl1MHF4JmfTp:bmdia04) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_tree.h#L123)):*
> ```objc
> 
>     Status dupKeyCheck(pool_base pop,BSONObj& key, const RecordId& loc);
>     p<int> _records = 0;
> ```

int or int64_t?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/38)*

**Comment by jschmieg** [comment]
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/pmse_change.cpp, line 101 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQLBLTK2TRo-hAY9W5:-KdQQvrwCjqrqczVH1Yo:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_change.cpp#L101)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If try or transaction fails what if?
_mapper->updateKV will add empty object.
</blockquote></details>

Done.

---

*[src/pmse_change.cpp, line 123 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQKOMpCDCfZWhgn-IY:-KdQRJFo3UPEO_HHphkq:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_change.cpp#L123)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

>                             [&] {
>                                 _tree->remove(_pop, _key, _loc, _dupsAllowed, _desc->keyPattern(), nullptr);
>                                 --(_tree->_records);
Strange formatting. 
Lambda function is still parameter, look above
</blockquote></details>

Done.

---

*[src/pmse_change.cpp, line 152 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQNoLHpRdtLY3HEdp7:-KdQRVThmxuotl-vpTNP:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_change.cpp#L152)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

>        [&] {
>                                 obj = pmemobj_tx_alloc(_key.objsize(), 1);
>                                 memcpy( (void*)obj.get(), _key.objdata(), _key.objsize());
>                                 bsonPM.data = obj;
>                                 status = _tree->insert(_pop, bsonPM, _loc, _ordering, _dupsAllowed);
>                                 if(status == Status::OK())
>                                 {
>                                     ++_tree->_records;
>                                 }
Indentation
</blockquote></details>

Done.

---

*[src/pmse_tree.h, line 123 at r1](https://reviewable.io:443/reviews/pmem/pmse/38#-KdQOkFu4BLuOLpiuh6l:-KdQRxkbUUnaYc25fzdG:b-pyivoz) ([raw file](https://github.com/pmem/pmse/blob/a5cd536e6ddab1dfabea9e82cea007a38866a4e6/src/pmse_tree.h#L123)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

int or int64_t?
</blockquote></details>

Changed to long long to be compliant with fullValidate() function parameters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/38)*

**Comment by KFilipek** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/38)*

**Comment by KFilipek** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/38#-:-KdQWhRxgr0LAgqFCBcc:bnfp4nl)*

**Pull request merged**
