### PR TITLE
Reverse cursor for capped collection

### LINKED ISSUE #16: Implement reverse cursor for capped collection
Some tests wants reverse cursor, like: capped.js, capped6.js.
Impacts 24 tests.
_find().sort( { $natural: -1 } )_ causes that _forward_ variable is set to 0.

### PR DESCRIPTION
**Pull request by KFilipek**
Implementation of reverse cursor.

Fixes #16

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/21)

### CODE REVIEW

**Comment by Maciuch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/pmse_record_store.cpp, line 134 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkN_nh1Ncxlhmm3HTo:-KbkN_nh1Ncxlhmm3HTp:b-j82ecw) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.cpp#L134)):*
> ```cpp
>                                     "Not allocated memory!");
>     id = mapper->insert(obj);
>     std::cout << obj  << ": " << id << std::endl;
> ```

no logs in the data insertion path! Especially to std::cout

---

*[src/pmse_record_store.cpp, line 183 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkNliphsWPWrvhIZWM:-KbkNliphsWPWrvhIZWN:b-7v0m6y) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.cpp#L183)):*
> ```cpp
>         rec = cursor.next();
>     while(rec != boost::none) {
>         std::cout << rec->id << std::endl;
> ```

logging via log(); is the info on id helpful?

---

*[src/pmse_record_store.h, line 104 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkOrHFJTBZTTefhDJ9:-KbkOrHFJTBZTTefhDJA:b-2qpn6o) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L104)):*
> ```objc
>     }
>     void moveBackward() {
>         std::cout << "moveBackward()" << std::endl;
> ```

no logs on method calls

---

*[src/pmse_record_store.h, line 120 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkP53kUV0TZlmbmtXb:-KbkP53kUV0TZlmbmtXc:b-7n6ug0) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L120)):*
> ```objc
>         }
>         if(_cur == nullptr) {
>             std::cout << "Ups, null _cur" << std::endl;
> ```

log()

---

*[src/pmse_record_store.h, line 123 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkP8ELr2TP7YEHQte5:-KbkP8ELr2TP7YEHQte6:b-4bstv7) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L123)):*
> ```objc
>             _eof = true;
>         }
> //        std::cout << "moved to " << _cur->idValue << std::endl;
> ```

remove commented line

---

*[src/pmse_record_store.h, line 209 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkPHhAzwAKT3QWv9zs:-KbkPHhAzwAKT3QWv9zt:blv0ggw) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L209)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>        if(forward) {
>             std::cout << "forward cursor!" << std::endl;
>         } else {
>             std::cout << "reverse cursor!" << std::endl;
>         }
</details>

why would we want to log that?

---

*[src/pmse_sorted_data_interface.cpp, line 66 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkPPAW6vSIh_Sj04F6:-KbkPPAW6vSIh_Sj04F7:b-s1fpbm) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_sorted_data_interface.cpp#L66)):*
> ```cpp
>                                        const BSONObj& key, const RecordId& loc,
>                                        bool dupsAllowed) {
>     std::cout << "PmseSortedDataInterface::insert " << (dupsAllowed ? "dups allowed" : "dups not allowed") << std::endl;
> ```

cut it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/21)*

**Comment by Maciuch** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/21)*

**Comment by KFilipek** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/pmse_record_store.cpp, line 134 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkN_nh1Ncxlhmm3HTo:-KbkXixRfEER2r7qrg-H:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.cpp#L134)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

no logs in the data insertion path! Especially to std::cout
</blockquote></details>

Done.

---

*[src/pmse_record_store.cpp, line 183 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkNliphsWPWrvhIZWM:-KbkXn5yzjHe-Djv0tnU:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.cpp#L183)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

logging via log(); is the info on id helpful?
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 104 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkOrHFJTBZTTefhDJ9:-KbkXrB1blFq1FMqD2di:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L104)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

no logs on method calls
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 120 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkP53kUV0TZlmbmtXb:-KbkXsb-3QETx8QqvPb4:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L120)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

log()
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 123 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkP8ELr2TP7YEHQte5:-KbkXu52frnw5i-oC3cR:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L123)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

remove commented line
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 209 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkPHhAzwAKT3QWv9zs:-KbkY2qO554UT3Xf4hfC:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_record_store.h#L209)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

>        if(forward) {
>             std::cout << "forward cursor!" << std::endl;
>         } else {
>             std::cout << "reverse cursor!" << std::endl;
>         }

why would we want to log that?

</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 66 at r1](https://reviewable.io:443/reviews/pmem/pmse/21#-KbkPPAW6vSIh_Sj04F6:-KbkY4c-AuM8WNMpeljj:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/8559ad5f862960a2745068c938c628ed7bdcb292/src/pmse_sorted_data_interface.cpp#L66)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

cut it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/21)*

**Comment by KFilipek** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/21)*

**Pull request merged**
