### PR TITLE
Collection truncate

### PR DESCRIPTION
**Pull request by KFilipek**
Implementation of truncate: 
db.collectionName.runCommand("emptycapped")

Fix half of test collection_truncate.js.
Test use also storageSize() and it will be implemented in another pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmse/7)

### CODE REVIEW

**Comment by Maciuch** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/pmse_map.h, line 152 at r1](https://reviewable.io:443/reviews/pmem/pmse/7#-K_VuRSColCVdAqp3YNz:-K_VuRSColCVdAqp3YO-:bpcols2) ([raw file](https://github.com/pmem/pmse/blob/c0789a2617b2a88a9693825b239dff9a3b72daec/src/pmse_map.h#L152)):*
> ```objc
>     }
> 
>     bool truncate() {
> ```

Apparently truncate() returns bool, therefore failure case should be handled.

void nvml::obj::delete_persistent ( typename detail::pp_if_not_array< T >::type ptr ) can throw:
transaction_scope_error	if called outside of an active transaction
transaction_alloc_error	on transactional free failure.
those should be caught and translated the the old style bool state return.

---

*[src/pmse_record_store.h, line 178 at r1](https://reviewable.io:443/reviews/pmem/pmse/7#-K_VveHeLpPlBh6Nw75h:-K_VveHeLpPlBh6Nw75i:b-rerjyo) ([raw file](https://github.com/pmem/pmse/blob/c0789a2617b2a88a9693825b239dff9a3b72daec/src/pmse_record_store.h#L178)):*
> ```objc
>     virtual Status truncate(OperationContext* txn) {
>         mapper->truncate();
>         return Status::OK();
> ```

rather truncate return state should be returned?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/7)*

**Comment by KFilipek** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/pmse_map.h, line 152 at r1](https://reviewable.io:443/reviews/pmem/pmse/7#-K_VuRSColCVdAqp3YNz:-K_eJCSTtgt34tQJkKQA:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/c0789a2617b2a88a9693825b239dff9a3b72daec/src/pmse_map.h#L152)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

Apparently truncate() returns bool, therefore failure case should be handled.

void nvml::obj::delete_persistent ( typename detail::pp_if_not_array< T >::type ptr ) can throw:
transaction_scope_error	if called outside of an active transaction
transaction_alloc_error	on transactional free failure.
those should be caught and translated the the old style bool state return.
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 178 at r1](https://reviewable.io:443/reviews/pmem/pmse/7#-K_VveHeLpPlBh6Nw75h:-K_eJFC5L3rjy_5Kwhul:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/c0789a2617b2a88a9693825b239dff9a3b72daec/src/pmse_record_store.h#L178)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

rather truncate return state should be returned?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/7)*

**Comment by Maciuch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/pmse_record_store.cpp, line 128 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fGcSkgAyn8SDhKx2I:-K_fGcSkgAyn8SDhKx2J:bqsusct) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.cpp#L128)):*
> ```cpp
>                                     "Null record Id!");
>     while(mapper->dataSize() > _storageSize) {
>         _storageSize =  _storageSize + 20480;
> ```

const it

---

*[src/pmse_record_store.cpp, line 150 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fGixdYqBMZSqLs4WB:-K_fGixdYqBMZSqLs4WC:b-94v8zk) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.cpp#L150)):*
> ```cpp
>     }
>     while(mapper->dataSize() > _storageSize) {
>         _storageSize =  _storageSize + 20480;
> ```

now you can see why const should be used :)

---

*[src/pmse_record_store.h, line 120 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fGy9ajV_7R8yLe9vc:-K_fGy9ajV_7R8yLe9vd:bd0f07i) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.h#L120)):*
> ```objc
>                                 BSONObjBuilder* extraInfo = NULL,
>                                 int infoLevel = 0) const {
>         // TODO: Implement storageSize
> ```

// is this todo still valid?

---

*[src/pmse_record_store.h, line 233 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fHB-TZOh_AeXDKoXs:-K_fHB-TZOh_AeXDKoXt:b-hgoucd) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.h#L233)):*
> ```objc
> private:
>     CappedCallback* _cappedCallback;
>     int64_t _storageSize = 20480;
> ```

where's that const?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/7)*

**Comment by Maciuch** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/pmse_record_store.cpp, line 150 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHJugdoZLRQ8TCfIDp:-KaHJugehdjDrIt-Uoss:by1i4k1) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_record_store.cpp#L150)):*
> ```cpp
>     }
>     while(mapper->dataSize() > _storageSize) {
>         _storageSize =  _storageSize + 20480;
> ```

still 20480

---

*[src/pmse_sorted_data_interface.cpp, line 760 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHOEY5BBrMBFTAVZzW:-KaHOEY5BBrMBFTAVZzX:b7o5gr4) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_sorted_data_interface.cpp#L760)):*
> ```cpp
>                     });
>     bsonPM.data = obj;
>     ++_records;
> ```

should be incremented within transaction

---

*[src/pmse_sorted_data_interface.cpp, line 772 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHOLe0NV4km2aurHca:-KaHOLe0NV4km2aurHcb:bgvncce) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_sorted_data_interface.cpp#L772)):*
> ```cpp
>                                          bool dupsAllowed) {
>     BSONObj owned = key.getOwned();
>     --_records;
> ```

should be removed within transaction

---

*[src/pmse_sorted_data_interface.h, line 90 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHHKCeQ_hg7V-nmc0W:-KaHHKCeQ_hg7V-nmc0X:be1ngug) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_sorted_data_interface.h#L90)):*
> ```objc
> 
>     virtual bool isEmpty(OperationContext* txn) {
>         // TODO: Implement isEmpty method
> ```

anything more to be done? remove //TODO if not you shall.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/7)*

**Comment by KFilipek** [comment]
Review status: 0 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/pmse_record_store.cpp, line 128 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fGcSkgAyn8SDhKx2I:-KaHaa8K4qbn3ybm317A:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.cpp#L128)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

const it
</blockquote></details>

Done.

---

*[src/pmse_record_store.cpp, line 150 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fGixdYqBMZSqLs4WB:-KaHac0Q7L3mKC4thAf2:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.cpp#L150)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

now you can see why const should be used :)
</blockquote></details>

Done.

---

*[src/pmse_record_store.cpp, line 150 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHJugdoZLRQ8TCfIDp:-KaHaasMdDp3bWNLM3Ml:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_record_store.cpp#L150)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

still 20480
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 120 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fGy9ajV_7R8yLe9vc:-KaHacwruk_jJGPC43fp:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.h#L120)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

// is this todo still valid?
</blockquote></details>

Done.

---

*[src/pmse_record_store.h, line 233 at r2](https://reviewable.io:443/reviews/pmem/pmse/7#-K_fHB-TZOh_AeXDKoXs:-KaHap0QNHNwCneTGZOl:bakg47t) ([raw file](https://github.com/pmem/pmse/blob/0a8837c0c5e6868332bb032238de84b9766d0716/src/pmse_record_store.h#L233)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

where's that const?
</blockquote></details>

Added in the top of file.

---

*[src/pmse_sorted_data_interface.cpp, line 760 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHOEY5BBrMBFTAVZzW:-KaHaghgeQ6iw5ZJ5jHd:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_sorted_data_interface.cpp#L760)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

should be incremented within transaction
</blockquote></details>

Done.

---

*[src/pmse_sorted_data_interface.cpp, line 772 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHOLe0NV4km2aurHca:-KaHahuJVCfiOzJ1u1yl:b-kdavr5) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_sorted_data_interface.cpp#L772)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

should be removed within transaction
</blockquote></details>

Jakub will change it with rebase.

---

*[src/pmse_sorted_data_interface.h, line 90 at r3](https://reviewable.io:443/reviews/pmem/pmse/7#-KaHHKCeQ_hg7V-nmc0W:-KaHanlvPsqk_XpwcVNH:b-896fix) ([raw file](https://github.com/pmem/pmse/blob/c4bba407511575ae33f3ddc3d68f4e159feb4cf6/src/pmse_sorted_data_interface.h#L90)):*
<details><summary><i>Previously, Maciuch (Maciej Maciejewski) wrote…</i></summary><blockquote>

anything more to be done? remove //TODO if not you shall.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/7)*

**Comment by Maciuch** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pmse/7#-:-KaHlVG8-S7uyCmudLR8:bnfp4nl)*

**Pull request merged**
